### ISSUE TITLE
add new cb client: consumer/resume-profile

### ISSUE THREAD

**Issue by yongzhu** [careerbuilder/ruby-cb-api#288]
hi team,

we try to call https://api.careerbuilder.com/consumer/resume-profile to convert job seeker profile into resume, but the API end pint does not include within ruby-cb-api repository now.

could your team to help code this api into repository, or we code it and make pull request to you?

thanks,

yong

**Comment by Casao** [comment]
Hi @yongzhu, I'll reach out to you on Hipchat
